# Colors (Tokyo Night Light)
# Source: https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night

[colors]
  primary.background = '#e6e7ed'
  primary.foreground = '#343b58'

  [colors.normal]
  black   = '#343b58'
  red     = '#8c4351'
  green   = '#385f0d'
  yellow  = '#8f5e15'
  blue    = '#2959aa'
  magenta = '#5a3e8e'
  cyan    = '#0f4b6e'
  white   = '#343b58'

  [colors.bright]
  black   = '#343b58'
  red     = '#8c4351'
  green   = '#385f0d'
  yellow  = '#8f5e15'
  blue    = '#2959aa'
  magenta = '#5a3e8e'
  cyan    = '#0f4b6e'
  white   = '#e6e7ed'
